set nocompatible
syntax on
set relativenumber
set autoindent
filetype on
set nobackup
set directory=/tmp
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set background=dark
colorscheme solarized
