#!/usr/bin/env sh

st="$HOME/Library/Application Support/Sublime Text 3/Packages/User"
rm -r "$st"
ln -s "$PWD/sublime" "$st"

defaults write -g ApplePressAndHoldEnabled -bool false
defaults write com.apple.Terminal TotalTerminalHideStatusItemRegardless -bool yes
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false

brew install caskroom/cask/brew-cask

brew install git zsh ack jq ngrok nmap rust flow sqlite python3 fzf \
             terminal-notifier leiningen brew-cask haskell-stack

brew cask install alfred google-chrome java transmission \
                  emacs dropbox iterm2 totalterminal vlc
