#!/usr/bin/env sh

st="$HOME/Library/Application Support/Sublime Text 3/Packages/User"
rm -r "$st"
ln -s "$PWD/sublime" "$st"

defaults write -g ApplePressAndHoldEnabled -bool false
defaults write com.apple.Terminal TotalTerminalHideStatusItemRegardless -bool yes

brew install caskroom/cask/brew-cask

brew install git zsh ack jq ngrok nmap rust flow sqlite node python3 \
             terminal-notifier fzf leiningen brew-cask haskell-stack

brew cask install alfred emacs google-chrome java transmission \
                  dropbox iterm2 totalterminal vlc
