#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

for file in .zshrc .zshenv .spacemacs .gitconfig .vimrc .tmux.conf .gitignore_global; do
  if [[ ! -s "$HOME/$file" ]]; then
    ln -s "$PWD/$file" "$HOME/$file"
  fi
done

mkdir -p "$HOME/bin/completions"

if [[ ! -e "$HOME/.emacs.d" ]]; then
  git clone --recursive https://github.com/syl20bnr/spacemacs "$HOME/.emacs.d"
fi
