#!/usr/bin/env bash

set -euo pipefail

SD_ROOT="$HOME/sd"
cd "$SD_ROOT"

while [[ $# > 0 ]]; do
  command="$1"
  shift
  if [[ -d "$command" ]]; then
    cd "$command"
  elif [[ -f "$command" ]]; then
    if [[ -x "$command" ]]; then
      "./$command" "$@"
      exit 0
    else
      # For now, this is my very low-tech help system...
      cat "$command"
      exit 0
    fi
  else
    echo "file not found!" >&2
    echo "$(pwd)/$command" >&2
    exit 1
  fi
done

echo "Commands:"
for file in $(find . -maxdepth 1 -mindepth 1 -not -name '*.help'); do
  helpfile="$file.help"
  help=""
  if [[ -f "$helpfile" ]]; then
    help=$(head -n1 "$helpfile")
  fi
  # well this is horrible but
  echo -e "                -- $help\r  $(basename "$file")"
done
